version: '3'

services:
  postgres:
    image: "postgres:latest"
    restart: "always"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - internal

  movie_service:
    image: kama93/movie.service:6
    restart: "always"
    environment:
      DB_HOST: infra_postgres_1
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      MOVIE_API_KEY: ${MOVIE_API_KEY}

networks:
  internal:
