version: '3'

services:
  postgres:
    image: "postgres:latest"
    restart: "always"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - internal

  movie_service:
    image: kama93/movie.service:7
    restart: "always"
    environment:
      DB_HOST: infra_postgres_1
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      MOVIE_API_KEY: ${MOVIE_API_KEY}
    networks:
      - internal

  movie_ui:
    image: kama93/movie:8
    restart: "always"
    environment:
      API_URL: http://infra_movie_service_1:3005/
    ports:
      - 8001:5000
    networks:
      - internal

  fit_service:
    image: kama93/fit.service:2
    restart: "always"
    environment:
      DB_HOST: infra_postgres_1
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      API_KEY: ${FIT_API_KEY}
    networks:
      - internal

  fit_ui:
    image: kama93/fit:2
    restart: "always"
    environment:
      API_URL: http://infra_fit_service_1:3003/
    ports:
      - 8002:5000
    networks:
      - internal

networks:
  internal:
