version: '3'

services:
  postgres:
    image: "postgres:12-alpine"
    restart: "always"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  mongo:
    image: "mongo"
    restart: "always"
    volumes:
      - /var/lib/mongo/db:/data/db

  about_me:
    image: kama93/about-me:latest
    restart: "always"

  byte_size:
    image: kama93/byte-size:latest
    restart: "always"

  drums:
    image: kama93/drums:latest
    restart: "always"

  robots:
    image: kama93/robots:latest
    restart: "always"

  movie_service:
    image: kama93/movie.service:latest
    restart: "always"
    environment:
      DB_HOST: kamila_postgres_1
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      MOVIE_API_KEY: ${MOVIE_API_KEY}

  movie_ui:
    image: kama93/movie:latest
    restart: "always"

  fit_service:
    image: kama93/fit.service:latest
    restart: "always"
    environment:
      DB_HOST: kamila_postgres_1
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      FOOD_API_KEY: ${FOOD_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      WAQI_API_KEY: ${WAQI_API_KEY}

  fit_ui:
    image: kama93/fit:latest
    restart: "always"

  face_service:
    image: kama93/face.service:latest
    restart: "always"
    environment:
      DB_HOST: kamila_postgres_1
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      CLARIFAI_API_KEY: ${CLARIFAI_API_KEY}

  face_ui:
    image: kama93/face:latest
    restart: "always"

  navbar:
    image: kama93/navbar:latest
    restart: "always"

  news_service:
    image: kama93/news.service:latest
    restart: "always"
    environment:
      MONGO_DB: kamila_mongo_1
      WEATHER_KEY: ${WEATHER_KEY}
      NEWS_KEY: ${NEWS_KEY}
      ALPHA_VANTAGE_KEY: ${ALPHA_VANTAGE_KEY}

  news_ui:
    image: kama93/news:latest
    restart: "always"

networks:
  default:
    external:
      name: ingress_default
