version: '3'

services:
  master:
    build:
      context: ./master
    volumes:
      - master_home:/jenkins
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  master_home:

networks:
  default:
    external:
      name: ingress_default
