version: '3'

services:
  master:
    build:
      context: ./master
    volumes:
      - master_home:/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
  build_cache:
    build:
      context: ./build_cache
    volumes:
      - build_cache:/cache

volumes:
  master_home:
  build_cache:

networks:
  default:
    external:
      name: ingress_default
