version: '3'

services:
  nginx:
    build:
      context: ./nginx
      args:
        apt_password: ${APT_PASSWORD}
    volumes:
      - ../nginx-sites/:/etc/nginx/conf.d/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - apt_repository:/var/lib/apt-repository/:ro
    ports:
      - 80:80
      - 443:443

volumes:
  apt_repository:
