version: '3'

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../nginx-sites/:/etc/nginx/conf.d/
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
